version: "3.9"

services:
  frontend:
    image: book-store-front:latest
    working_dir: /store-frontend
    volumes:
      - ./frontend:/store-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bookStoreNetwork
  backend:
    image: book-store-back:latest
    working_dir: /store-backend
    volumes: 
      - ./backend:/store-backend
    ports: 
      - "8080:8080"
    networks:
      - bookStoreNetwork

networks:
  bookStoreNetwork: